### ISSUE TITLE
License, attribution/distribution

### ISSUE THREAD

**Issue by et1975** [csoren/elmish-sample#1]
Hey, kudos on the valiant attempt to bring sanity to Xamarin forms programming!
Couple of observations: 
- your license file is incomplete, and without filling out {} placeholders it's basically void.
- your redistribution of [elmish](https://github.com/fable-elmish/elmish) code needs to follow clause#4 of the license.

Since there are now two non-fable targets, I wonder if there is a value in amending the core to be consumable directly by WPF/Xamarin in the DLL form... it's already targeting netstandard and includes the actual IL. cc @2sComplement

**Comment by csoren** [comment]
Hi Eugene. Thanks for pointing out the license mistake. Regarding redistribution of elmish, that's probably more relevant to the [elmish-xamarin-forms](https://github.com/csoren/elmish-xamarin-forms) project, but I'll make sure to fix it where it needs fixing 

Making the Elmish core consumable directly would be great!

**Comment by csoren** [comment]
I have updated the license for this repo and [elmish-xamarin-forms](https://github.com/csoren/elmish-xamarin-forms). I have added your license and a notice stating the file has been modified to cmd.fs and programs.fs. Does this look good to you?
